name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  tag:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: |
          if [[ "${{ github.ref }}" == v1.* ]]
          then
            echo "BUILD_BRANCH=v1" >> $GITHUB_ENV
          else
            echo "BUILD_BRANCH=master" >> $GITHUB_ENV
          fi
      - name: Create release tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            [CHANGELOG.md](https://github.com/hujiulong/vue-3d-model/blob/${{ env.BUILD_BRANCH }}/CHANGELOG.md)
      
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Get branch name
        run: |
          if [[ "${{ github.ref }}" == v1.* ]]
          then
            echo "BUILD_BRANCH=v1" >> $GITHUB_ENV
          else
            echo "BUILD_BRANCH=master" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
        with:
          branch: ${{ env.BUILD_BRANCH }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Build & publish
        run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish to GPR
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Get branch name
        run: |
          if [[ "${{ github.ref }}" == v1.* ]]
          then
            echo "BUILD_BRANCH=v1" >> $GITHUB_ENV
          else
            echo "BUILD_BRANCH=master" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
        with:
          branch: ${{ env.BUILD_BRANCH }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@hujiulong'
      - name: Build & publish
        run: |
          npm install
          npm run build
          npm run gpr-setup
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}